---
steps:
  - name: "Build"
    command: "script/build"

  - wait

  - command: "script/deploy_wrap.sh development"
    label: "Deploy to Development"
    branches: "master"

  - command: "script/deploy_wrap.sh production"
    label: "Deploy to Production"
    branches: "v*.*.*"
    #Branch filters also imply Tag filter.
    #Make sure "Build Tags" is checked in the Github settings for the project

  - trigger: democracy-works-kubernetes
    label: "Deploy to legacy k8s"
    branches: master
    async: true
    build:
      branch: master
      env:
        DW_COMPONENT: {{name}}
        SOURCE_JOB_ID: "${BUILDKITE_JOB_ID}"
