#!/usr/bin/env bash
set -o errexit

. script/env.sh

docker-pull -f deploy/build.config

echo '--- building docker image'
{{#datomic?}}
if [[ ! -e "profiles.clj" ]]; then echo '{}' > profiles.clj; fi
ROK8S_DOCKER_BUILD_EXTRAARGS=\
  "--build-arg DATOMIC_USERNAME=$DATOMIC_USERNAME \
   --build-arg DATOMIC_PASSWORD=$DATOMIC_PASSWORD" \
{{/datomic?}}
docker-build -f deploy/build.config

docker-push -f deploy/build.config

if hash buildkite-agent 2>/dev/null ; then
  echo '--- saving container-image metadata for legacy k8s deploy'
  buildkite-agent meta-data set container-image ${DOCKERTAG}:${BUILDKITE_COMMIT}
fi
