steps:
- label: "Build"
  command: "script/build"
  plugins:
  - docker#v3.8.0:
      image: quay.io/democracyworks/reactiveops-ci-images:latest
      always-pull: true
      propagate-environment: true
      volumes:
      - "${HOME}/.docker:/root/.docker:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
  timeout_in_minutes: 15
